[package]
name = "chatclient"
version = "0.1.0"
edition = "2021"

[dependencies]
colog = "1.3.0"
crossterm = "0.28.1"
futures = "0.3.31"
log = "0.4.22"
ratatui = "0.29.0"
tokio = { version = "1.41.1", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["codec"] }
